# Generated by Django 2.2.5 on 2022-01-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_zone', '0002_auto_20220125_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.IntegerField()),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('is_like', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
        migrations.AlterField(
            model_name='feed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['feed_id'], name='photo_zone__feed_id_907389_idx'),
        ),
    ]
