# Generated by Django 2.2.5 on 2022-01-26 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulletin', '0002_alter_bulletinfeed_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinfeed',
            old_name='upload_time',
            new_name='write_date',
        ),
        migrations.AddField(
            model_name='bulletinfeed',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bulletinfeed',
            name='reply_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bulletinfeed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='BulletinReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('bulletinfeed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bulletin.BulletinFeed')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
