# Generated by Django 2.2.5 on 2022-01-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_alter_bulletinfeed_id_alter_bulletinreply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinfeed',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bulletinreply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
